const calloutCustomerSteps = [
  {
    key: "customerName",
    title: "Enter your full name",
    summaryLabel: "Customer name",
    kind: "input",
    inputType: "text",
    placeholder: "Full name",
    helperText: "We use this on your booking confirmation.",
  },
  {
    key: "customerPhone",
    title: "Enter your phone number",
    summaryLabel: "Customer phone",
    kind: "input",
    inputType: "tel",
    placeholder: "e.g. 082 000 0000",
    helperText: "This helps Cleanstep contact you if needed.",
  },
];

export const services = {
  footwear: {
    id: "footwear",
    checkoutMode: "contact",
    title: "Footwear Cleaning",
    href: "/shoes",
    description:
      "Standard washes, suede treatment, refurbish jobs and bag cleaning in one premium booking flow.",
    steps: [
      {
        key: "category",
        title: "Select footwear category",
        kind: "options",
        options: [
          { name: "Ordinary Sneakers & Shoes", value: "ordinary" },
          { name: "Suede, Nubuck & Leather", value: "suede" },
          { name: "Refurbish / Express", value: "refurbish" },
          { name: "Bags", value: "bags" },
        ],
      },
      {
        key: "variant",
        title: "Select treatment or item",
        kind: "options",
        dependsOn: ["category"],
        options: [
          { name: "Other colours", value: "ordinary-other", category: "ordinary", price: 130 },
          { name: "White", value: "ordinary-white", category: "ordinary", price: 140 },
          { name: "Boots", value: "ordinary-boots", category: "ordinary", price: 160 },
          { name: "Other colours", value: "suede-other", category: "suede", price: 140 },
          { name: "White / Cream", value: "suede-white", category: "suede", price: 150 },
          { name: "Boots", value: "suede-boots", category: "suede", price: 170 },
          { name: "Same day", value: "refurbish-sameday", category: "refurbish", price: 210 },
          { name: "Next day", value: "refurbish-nextday", category: "refurbish", price: 190 },
          { name: "Deep Cleaning", value: "refurbish-deep", category: "refurbish", price: 190 },
          { name: "Restore Colour", value: "refurbish-restore", category: "refurbish", price: 250 },
          {
            name: "Handbags",
            value: "bag-handbag",
            category: "bags",
            price: 160,
            priceLabel: "From R160",
            pricingNote: "Final price can increase depending on size and material.",
          },
          {
            name: "Backpacks",
            value: "bag-backpack",
            category: "bags",
            price: 160,
            priceLabel: "From R160",
            pricingNote: "Final price can increase depending on size and material.",
          },
        ],
      },
      {
        key: "quantity",
        title: "How many items are you booking?",
        kind: "number",
        min: 1,
        max: 10,
        defaultValue: 1,
        unitLabel: "items",
        helperText: "Set the number of pairs, bags or footwear items in this booking.",
      },
    ],
  },

  carpets: {
    id: "carpets",
    checkoutMode: "contact",
    title: "Carpets Cleaning",
    href: "/carpets",
    description:
      "Loose carpets, fitted domestic carpets and commercial sqm-based cleaning with clear pricing logic.",
    steps: [
      {
        key: "type",
        title: "Select carpet type",
        kind: "options",
        options: [
          { name: "Loose Carpets", value: "loose" },
          { name: "Domestic (Fitted Carpets)", value: "domestic" },
          { name: "Commercial Carpets", value: "commercial" },
        ],
      },
      {
        key: "family",
        title: "Select carpet category",
        kind: "options",
        dependsOn: ["type"],
        options: [
          {
            name: "Standard Carpets",
            value: "standard",
            type: "loose",
            pricingNote: "Standard loose carpet pricing follows the left column of the Cleanstep list.",
          },
          {
            name: "Persian Carpets",
            value: "persian",
            type: "loose",
            pricingNote: "Persian carpet pricing follows the right column of the Cleanstep list.",
          },
          { name: "Domestic Rooms", value: "domestic-room", type: "domestic" },
          {
            name: "Commercial Area Pricing",
            value: "commercial-area",
            type: "commercial",
            pricingNote: "Price is calculated per sqm according to the selected area band.",
          },
        ],
      },
      {
        key: "package",
        title: "Select final carpet option",
        kind: "options",
        dependsOn: ["type", "family"],
        showWhen: {
          type: ["loose", "domestic"],
        },
        options: [
          {
            name: "Standard Small (up to 1.4m²)",
            value: "standard-small",
            type: "loose",
            family: "standard",
            price: 190,
          },
          {
            name: "Standard Medium (2m x 1.2m)",
            value: "standard-medium",
            type: "loose",
            family: "standard",
            price: 440,
          },
          {
            name: "Standard Large (1.3m x 3m)",
            value: "standard-large",
            type: "loose",
            family: "standard",
            price: 530,
          },
          {
            name: "Standard X-Large (2.6m x 5m)",
            value: "standard-xlarge",
            type: "loose",
            family: "standard",
            price: 690,
          },
          {
            name: "Persian Small",
            value: "persian-small",
            type: "loose",
            family: "persian",
            price: 250,
          },
          {
            name: "Persian Medium",
            value: "persian-medium",
            type: "loose",
            family: "persian",
            price: 550,
          },
          {
            name: "Persian Large",
            value: "persian-large",
            type: "loose",
            family: "persian",
            price: 650,
          },
          {
            name: "Persian X-Large",
            value: "persian-xlarge",
            type: "loose",
            family: "persian",
            price: 790,
          },
          {
            name: "Small Bedroom",
            value: "domestic-small-bedroom",
            type: "domestic",
            family: "domestic-room",
            price: 550,
          },
          {
            name: "Big Bedroom",
            value: "domestic-big-bedroom",
            type: "domestic",
            family: "domestic-room",
            price: 690,
          },
          {
            name: "Lounge Carpets",
            value: "domestic-lounge",
            type: "domestic",
            family: "domestic-room",
            price: 890,
          },
        ],
      },
      {
        key: "area",
        title: "Enter commercial carpet area",
        kind: "number",
        min: 1,
        max: 5000,
        defaultValue: 100,
        unitLabel: "sqm",
        helperText: "0-100 sqm = R22/sqm, 101-400 sqm = R20/sqm, 401+ sqm = R18/sqm.",
        showWhen: {
          type: "commercial",
        },
      },
      {
        key: "location",
        title: "Enter the cleaning location",
        summaryLabel: "Service location",
        kind: "place",
        inputType: "text",
        placeholder: "Suburb, street name or full address",
        helperText: "Required for fitted and commercial carpets so the team knows where to go.",
        showWhen: {
          type: ["domestic", "commercial"],
        },
      },
      {
        key: "bookingDate",
        title: "Choose a preferred date",
        summaryLabel: "Preferred date",
        kind: "input",
        inputType: "date",
        helperText: "Choose the date you want the cleaning team to come out.",
        showWhen: {
          type: ["domestic", "commercial"],
        },
      },
      ...calloutCustomerSteps.map((step) => ({
        ...step,
        showWhen: {
          type: ["domestic", "commercial"],
        },
      })),
    ],
  },

  upholstery: {
    id: "upholstery",
    checkoutMode: "contact",
    title: "Beds, Couches & Cushions",
    href: "/couches",
    description:
      "Book mattress and couch deep cleaning with the same step-by-step premium flow.",
    steps: [
      {
        key: "category",
        title: "Select item category",
        kind: "options",
        options: [
          { name: "Mattress", value: "mattress" },
          { name: "Couch", value: "couch" },
        ],
      },
      {
        key: "variant",
        title: "Select size or seating option",
        kind: "options",
        dependsOn: ["category"],
        options: [
          { name: "Single", value: "mattress-single", category: "mattress", price: 350 },
          { name: "Double", value: "mattress-double", category: "mattress", price: 490 },
          { name: "Queen", value: "mattress-queen", category: "mattress", price: 550 },
          { name: "King", value: "mattress-king", category: "mattress", price: 590 },
          { name: "Chair", value: "couch-chair", category: "couch", price: 180 },
          { name: "1 Seater", value: "couch-1", category: "couch", price: 350 },
          { name: "2 Seater", value: "couch-2", category: "couch", price: 490 },
          { name: "3 Seater", value: "couch-3", category: "couch", price: 580 },
          { name: "4 Seater", value: "couch-4", category: "couch", price: 710 },
          { name: "5 Seater", value: "couch-5", category: "couch", price: 920 },
          { name: "6 Seater", value: "couch-6", category: "couch", price: 1180 },
        ],
      },
      {
        key: "quantity",
        title: "How many items are you booking?",
        kind: "number",
        min: 1,
        max: 10,
        defaultValue: 1,
        unitLabel: "items",
        helperText: "Adjust the number of mattresses or couch units in this booking.",
      },
      {
        key: "location",
        title: "Enter the cleaning location",
        summaryLabel: "Service location",
        kind: "place",
        inputType: "text",
        placeholder: "Suburb, street name or full address",
        helperText: "Enter the call-out address so the team knows where to come.",
      },
      {
        key: "bookingDate",
        title: "Choose a preferred date",
        summaryLabel: "Preferred date",
        kind: "input",
        inputType: "date",
        helperText: "Choose the date you want the Cleanstep team to come out.",
      },
      ...calloutCustomerSteps,
    ],
  },
};
